### ISSUE TITLE
Resource apim_flexgateway upstream_uri / endpoint_uri behaviour

### ISSUE THREAD

**Issue by ralex** [mulesoft-anypoint/terraform-provider-anypoint#55] opened 2024-11-06 16:43 UTC
I'm trying to deploy our existing APIs and policies with anypoint provider.

After importing `apim_flexgateway` resources, I've been able to deploy everything perfectly until production where `endpoint_uri` is defined.
This was done previously by adding the public URL of our API in the "Consumer endpoint" filed in Anypoint UI.

The issue is that the `upstream_uri` has been overwritten by `endpoint_uri` value.
It was 100% written in the documentation, so I should have anticipated it.

> Create an API Manager Instance of type Flex Gateway. When an API instance of type Flex Gateway is created, it has automatically a default upstream linked to the endpoint_uri and a routing that points to this one. This provider will remove all default routings and upstreams.

The goal of this field is to be able to display this information to end user so they can retrieve the public URL of our service.
I think I'm missing the point why it is a good idea to put it in `upstream_uri`.

Also I've tried to declare multiple upstreams as a workaround but it seems that I can't do it actually with Flex Gateway version 1.7.1 and anypoint provider in version 1.7.0.

**Comment by soufi** [comment] 2024-11-08 19:50
Hi @ralex, would you be able to send an example ? with the expected behaviour ?

**Comment by ralex** [comment] 2024-11-12 09:00
Hello @soufi,

Thanks for your quick response.
Here is a code sample based on my configuration:
```
resource "anypoint_apim_flexgateway" "fg" {
  org_id                     = var.anypoint_org_id
  env_id                     = var.anypoint_env_id
  asset_group_id             = var.anypoint_org_id
  asset_id                   = var.anypoint_asset_id
  asset_version              = var.anypoint_asset_version
  deployment_target_id       = var.anypoint_flex_gateway_id
  deployment_target_name     = "flex-gateway-${var.environment}"
  deployment_gateway_version = var.anypoint_flex_gateway_version
  instance_label             = "${var.environment}-${var.instance_label_suffix}"
  endpoint_proxy_uri         = "http://0.0.0.0:8080/path/prefix"

  upstreams {
    uri   = var.anypoint_upstream_uri
    label = "default"
  }

  routing {
    label = "default"
    upstreams {
      label  = "default"
      weight = 100
    }
  }
}
```

I applied this code to imported resources.

In non-production environments, the deployment worked as expected, since the "Consumer endpoint" field in the Anypoint API Manager UI was left blank.

However, when deploying to production, as the "Consumer endpoint" was populated, it ended up in the read-only configuration argument `endpoint_uri` and the `upstream_uri` was overwritten by its value.

**Comment by soufi** [comment] 2024-11-23 14:59
This will take more time than expected because I don't have a proper environment to test, our anypoint license account just expired.

**Comment by soufi** [comment] 2024-12-22 18:01
Hi @ralex, 
I just the time and material to look into this. 
1. Regarding your first remark,  `The issue is that the upstream_uri has been overwritten by endpoint_uri value.`:  This is a limitation that is coming from the Anypoint API. there are some parameters that we can't set when creating the flex gateway api. you have to create and then follow it with an update. You can see this on the UI of anypoint for example, you can't set the consumer endpoint when you create the API, you have to wait until you create it to add it ... 
The plugin tried to do all of this automatically to simplify things, but it's still painful.
But once the API is created, you can set the value and update it with terraform.

**Comment by ralex** [comment] 2024-12-26 09:59
Hi @soufi,
Thank you for taking the time to look at it.

I understand, the behaviour I had is probably related to fact I imported this API.
I will try to configure consumer endpoint on others APIs freshly created with terraform and see if the configuration sticks on next terraform apply.

**Comment by soufi** [comment] 2024-12-26 18:54
I will close this one then. If you have any weird behaviour feel free to open another one.

**Closed by soufi** 2024-12-26 18:54 UTC
Labels: question
